# Generated by Django 3.2 on 2022-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de nacimiento')),
                ('cedula_identidad', models.IntegerField(blank=True, null=True, verbose_name='Cédula Identidad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última modificación')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
    ]
