# Generated by Django 3.2 on 2022-08-26 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('familiarum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_completo',
            field=models.CharField(default='', max_length=250, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
